name: Test

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: 1
      TERM: xterm-color
      MYPY_FORCE_COLOR: 1
      MYPY_FORCE_TERMINAL_WIDTH: 200
      PYTEST_ADDOPTS: --color=yes

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Pip install
        run: make install

      - name: Run ruff
        run: make ruff

      - name: Run mypy
        run: make mypy

      - name: Run black
        run: make black

      - name: Run isort
        run: make isort

      - name: Run unit tests
        run: make test

      - name: Self test
        run: make self-test
